algorithm.total_steps: 4_000_000 
algorithm.save_interval: 200_000
algorithm.video_interval: 200_000
algorithm.video_frames: 1000
algorithm.log_interval: 100_000
algorithm.eval_interval: 100_000
algorithm.eval_episodes: 100

algorithm.standardise_rewards: True
algorithm.model.parameter_sharing: True
algorithm.model.use_rnn: True
algorithm.eps_decay_over: 0.1

env.name: smaclite/2s_vs_1sc-v0
  # - smaclite/3s5z-v0
env.time_limit: 150
"+env.use_cpp_rvo2": True
"+algorithm":
  - "idqn"
  - "qmix"
  - "vdn"
